#bad jokes - shows string functions
print ('what do you get if you cross a snowman with a vampire')
input()
print ('Frostbite!')
print()
print('what do dentists call an astronaut\'s cavity?')
input() 
print('A black hole')
print()
print('Knock knock.')
input()
print ("Who's there?")
input()
print ('interrupting cow')
input()
print('Interupting cow wh',end='')
print ('-MOO!')
